# Ahmet Numan Aytemiz's Blog Pages
title: Network Security Blog
author:
  name: Ahmet Numan Aytemiz
  email: ahmetnumanaytemiz@gmail.com
description: "My Labs, Notes and Blogs about Network and Security"

# Build settings
theme: jekyll-theme-hacker